// projects/klini-ds/src/lib/components/timeline/timeline.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { TimelineModule } from 'primeng/timeline';
import { CommonModule } from '@angular/common';

export interface KliniTimelineEvent {
  status?: string;
  date?: string;
  icon?: string;
  color?: string;
  content?: string;
  [key: string]: unknown;
}

@Component({
  selector: 'kln-timeline',
  standalone: true,
  imports: [CommonModule, TimelineModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <p-timeline
      [value]="events"
      [align]="align"
      [layout]="layout"
      [styleClass]="'kln-timeline ' + styleClass"
    >
      <ng-template pTemplate="marker" let-event>
        <span class="kln-timeline__marker" [style.background]="event.color || 'var(--klini-action-primary)'">
          @if (event.icon) { <i [class]="event.icon"></i> }
        </span>
      </ng-template>
      <ng-template pTemplate="content" let-event>
        <div class="kln-timeline__content">
          @if (event.status) { <p class="kln-timeline__status">{{ event.status }}</p> }
          @if (event.date) { <small class="kln-timeline__date">{{ event.date }}</small> }
          @if (event.content) { <p class="kln-timeline__text">{{ event.content }}</p> }
        </div>
      </ng-template>
    </p-timeline>
  `,
  styles: [`
    .kln-timeline__marker { display:flex; align-items:center; justify-content:center; width:2rem; height:2rem; border-radius:50%; color:#fff; font-size:.875rem; }
    .kln-timeline__status { font-weight:600; color:var(--klini-text-primary); font-family:'Plus Jakarta Sans',sans-serif; margin:0; }
    .kln-timeline__date { color:var(--klini-text-muted); font-size:var(--klini-font-size-caption); }
    .kln-timeline__text { color:var(--klini-text-secondary); font-size:var(--klini-font-size-body-sm); margin:var(--klini-space-1) 0 0; }
  `],
})
export class KliniTimelineComponent {
  @Input({ required: true }) events: KliniTimelineEvent[] = [];
  @Input() align: 'left' | 'right' | 'alternate' = 'left';
  @Input() layout: 'vertical' | 'horizontal' = 'vertical';
  @Input() styleClass = '';
}

// react/src/components/ui/timeline.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

export interface TimelineEvent {
  status?: string
  date?: string
  icon?: React.ReactNode
  color?: string
  content?: string
}

export interface TimelineProps extends React.HTMLAttributes<HTMLDivElement> {
  events: TimelineEvent[]
  align?: "left" | "right" | "alternate"
  layout?: "vertical" | "horizontal"
}

const Timeline = React.forwardRef<HTMLDivElement, TimelineProps>(
  ({ className, events, align = "left", layout = "vertical", ...props }, ref) => (
    <div
      ref={ref}
      className={cn("flex", layout === "vertical" ? "flex-col" : "flex-row", className)}
      {...props}
    >
      {events.map((event, index) => {
        const isAlternateRight = align === "alternate" && index % 2 === 1
        const reversed = align === "right" || isAlternateRight

        return (
          <div
            key={index}
            className={cn(
              "flex gap-3",
              layout === "vertical" ? "flex-1" : "flex-col items-center",
              reversed && layout === "vertical" && "flex-row-reverse text-right"
            )}
          >
            <div className="flex flex-col items-center">
              <span
                className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-sm text-white"
                style={{ background: event.color ?? "hsl(var(--primary))" }}
              >
                {event.icon}
              </span>
              {index < events.length - 1 && (
                <span
                  className={cn("bg-border", layout === "vertical" ? "w-px flex-1" : "h-px flex-1 w-8")}
                />
              )}
            </div>
            <div className={cn("pb-6", layout === "horizontal" && "pb-0 pt-2 text-center")}>
              {event.status && <p className="font-semibold">{event.status}</p>}
              {event.date && <p className="text-xs text-muted-foreground">{event.date}</p>}
              {event.content && <p className="mt-1 text-sm text-muted-foreground">{event.content}</p>}
            </div>
          </div>
        )
      })}
    </div>
  )
)
Timeline.displayName = "Timeline"

export { Timeline }
