// react/src/components/ui/meter-group.tsx
import * as React from "react"

import { cn } from "@/lib/utils"

export interface MeterItem {
  label?: string
  value: number
  color?: string
}

export interface MeterGroupProps {
  value: MeterItem[]
  max?: number
  orientation?: "horizontal" | "vertical"
  labelPosition?: "start" | "end"
  indicatorValue?: number | null
  indicatorUnit?: string
  className?: string
}

const MeterGroup = React.forwardRef<HTMLDivElement, MeterGroupProps>(
  ({ value, max = 100, orientation = "horizontal", labelPosition = "end", indicatorValue = null, indicatorUnit = "", className }, ref) => {
    const indicatorPercent =
      indicatorValue !== null ? (Math.max(0, Math.min(max, indicatorValue)) / max) * 100 : null

    const bar = (
      <div
        className={cn(
          "flex overflow-hidden rounded-full bg-muted",
          orientation === "horizontal" ? "h-3 w-full" : "h-40 w-3 flex-col-reverse"
        )}
      >
        {value.map((item, index) => {
          const percent = (item.value / max) * 100
          return (
            <div
              key={index}
              style={{
                [orientation === "horizontal" ? "width" : "height"]: `${percent}%`,
                background: item.color ?? "hsl(var(--primary))",
              }}
              title={item.label}
            />
          )
        })}
      </div>
    )

    const labels = (
      <div className="flex flex-wrap gap-x-4 gap-y-1">
        {value.map((item, index) => (
          <span key={index} className="flex items-center gap-1.5 text-xs text-muted-foreground">
            <span className="h-2 w-2 rounded-full" style={{ background: item.color ?? "hsl(var(--primary))" }} />
            {item.label}
          </span>
        ))}
      </div>
    )

    return (
      <div ref={ref} className={cn("flex flex-col gap-2", className)}>
        {indicatorPercent !== null && (
          <div className="relative h-3">
            <div
              className="absolute -translate-x-1/2 text-foreground transition-[left] duration-300"
              style={{ left: `${indicatorPercent}%` }}
              aria-label={`Valor atual: ${indicatorValue}${indicatorUnit ? ` ${indicatorUnit}` : ""}`}
            >
              <svg width="12" height="9" viewBox="0 0 12 9" fill="none">
                <path d="M6 9L0.803848 0.75L11.1962 0.75L6 9Z" fill="currentColor" />
              </svg>
            </div>
          </div>
        )}
        {labelPosition === "start" && labels}
        {bar}
        {labelPosition === "end" && labels}
      </div>
    )
  }
)
MeterGroup.displayName = "MeterGroup"

export { MeterGroup }

// projects/klini-ds/src/lib/components/meter-group/meter-group.component.ts
/**
 * kln-meter-group — wrapper PrimeNG p-metergroup
 *
 * Variante padrão:
 *   <kln-meter-group [value]="items" />
 *
 * Variante WithIndicator (Zone Bar — pressão arterial, glicemia, IMC):
 *   Exibe um ponteiro triangular na posição do valor atual sobre a barra.
 *   <kln-meter-group [value]="zones" [indicatorValue]="128" [max]="200" />
 *   O indicador usa os tokens de status do DS (--kln-chart-status-*).
 */
import { ChangeDetectionStrategy, Component, Input, OnChanges } from '@angular/core';
import { MeterGroupModule, MeterItem } from 'primeng/metergroup';

@Component({
  selector: 'kln-meter-group',
  standalone: true,
  imports: [MeterGroupModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="kln-meter-group-wrap">
      @if (indicatorValue !== null) {
        <div class="kln-meter-group-wrap__indicator-row">
          <div
            class="kln-meter-group-wrap__indicator"
            [style.left]="indicatorPercent + '%'"
            [attr.aria-label]="'Valor atual: ' + indicatorValue + (indicatorUnit ? ' ' + indicatorUnit : '')"
          >
            <svg width="12" height="9" viewBox="0 0 12 9" fill="none" aria-hidden="true">
              <path d="M6 9L0.803848 0.75L11.1962 0.75L6 9Z" fill="currentColor"/>
            </svg>
          </div>
        </div>
      }

      <p-metergroup
        [value]="value"
        [max]="max"
        [orientation]="orientation"
        [labelPosition]="labelPosition"
        [styleClass]="'kln-meter-group ' + styleClass"
      />
    </div>
  `,
  styles: [`
    .kln-meter-group-wrap {
      display: block;
    }

    .kln-meter-group-wrap__indicator-row {
      position: relative;
      height: 14px;
      margin-bottom: 2px;
    }

    .kln-meter-group-wrap__indicator {
      position: absolute;
      transform: translateX(-50%);
      color: var(--kln-text-primary, #374151);
      transition: left 0.3s ease;
      line-height: 0;
    }
  `],
})
export class KlnMeterGroupComponent implements OnChanges {
  /** Segmentos da barra — cada item tem label, value, color */
  @Input({ required: true }) value: MeterItem[] = [];
  /** Valor máximo total da barra */
  @Input() max = 100;
  @Input() orientation: 'horizontal' | 'vertical' = 'horizontal';
  @Input() labelPosition: 'start' | 'end' = 'end';
  @Input() styleClass = '';

  /**
   * Variante WithIndicator: valor atual a ser marcado com ponteiro triangular.
   * null = comportamento padrão sem indicador.
   */
  @Input() indicatorValue: number | null = null;
  /** Unidade exibida no aria-label do indicador (ex: 'mmHg', 'bpm') */
  @Input() indicatorUnit = '';

  indicatorPercent = 0;

  ngOnChanges(): void {
    if (this.indicatorValue !== null) {
      const clamped = Math.max(0, Math.min(this.max, this.indicatorValue));
      this.indicatorPercent = (clamped / this.max) * 100;
    }
  }
}
